//
// Generated by afu_json_mgr from ../hw/afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "afu"
#define AFU_ACCEL_UUID "94DD2B43-C2AD-4C5C-8D6A-2098F9277842"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
